# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uAum7KJ4EjCpxPklWWgWRMxKOjxEE9o0
"""

import math

def calculate(input):
    return -sum(i * math.log2(i) for i in input if i > 0)

A= 10/20
B= 5/20
C= 3/20
D= 2/20
E= 0/20
F= 0/20

entropia = calculate([A, B, C, D, E, F])
print(f"Entropia: {entropia}")